# -*- mode: python ; coding: utf-8 -*-
import os
import sys

# Get project paths
project_root = os.path.dirname(os.path.abspath(SPECPATH))

# Analysis
a = Analysis(
    ['main.py'],
    pathex=[project_root],
    binaries=[],
    datas=[
        ('template_app/assets', 'template_app/assets'),
        ('launcher_config.json', '.'),
    ],
    hiddenimports=[
        'PySide6',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets.QApplication',
        'PySide6.QtWidgets.QMainWindow',
        'PySide6.QtWidgets.QWidget',
        'PySide6.QtWidgets.QVBoxLayout',
        'PySide6.QtWidgets.QHBoxLayout',
        'PySide6.QtWidgets.QGridLayout',
        'PySide6.QtWidgets.QLabel',
        'PySide6.QtWidgets.QLineEdit',
        'PySide6.QtWidgets.QPushButton',
        'PySide6.QtWidgets.QFrame',
        'PySide6.QtWidgets.QTextEdit',
        'PySide6.QtWidgets.QScrollArea',
        'PySide6.QtWidgets.QSizePolicy',
        'PySide6.QtWidgets.QFileDialog',
        'PySide6.QtWidgets.QMessageBox',
        'PySide6.QtWidgets.QMenu',
        'PySide6.QtWidgets.QMenuBar',
        'PySide6.QtWidgets.QStatusBar',
        'PySide6.QtWidgets.QToolBar',
        'PySide6.QtWidgets.QSplitter',
        'PySide6.QtWidgets.QTabWidget',
        'PySide6.QtWidgets.QComboBox',
        'PySide6.QtWidgets.QCheckBox',
        'PySide6.QtWidgets.QRadioButton',
        'PySide6.QtWidgets.QSlider',
        'PySide6.QtWidgets.QProgressBar',
        'PySide6.QtWidgets.QSpinBox',
        'PySide6.QtWidgets.QDoubleSpinBox',
        'PySide6.QtWidgets.QDateEdit',
        'PySide6.QtWidgets.QTimeEdit',
        'PySide6.QtWidgets.QDateTimeEdit',
        'PySide6.QtWidgets.QCalendarWidget',
        'PySide6.QtWidgets.QListWidget',
        'PySide6.QtWidgets.QTreeWidget',
        'PySide6.QtWidgets.QTableWidget',
        'PySide6.QtWidgets.QGroupBox',
        'PySide6.QtWidgets.QStackedWidget',
        'PySide6.QtCore.Qt',
        'PySide6.QtCore.QTimer',
        'PySide6.QtCore.QPropertyAnimation',
        'PySide6.QtCore.QEasingCurve',
        'PySide6.QtCore.QRect',
        'PySide6.QtCore.QSize',
        'PySide6.QtCore.QPoint',
        'PySide6.QtCore.QThread',
        'PySide6.QtCore.QSignal',
        'PySide6.QtCore.QSlot',
        'PySide6.QtCore.QObject',
        'PySide6.QtCore.QEvent',
        'PySide6.QtCore.QFileInfo',
        'PySide6.QtCore.QMimeData',
        'PySide6.QtGui.QFont',
        'PySide6.QtGui.QPalette',
        'PySide6.QtGui.QColor',
        'PySide6.QtGui.QPixmap',
        'PySide6.QtGui.QPainter',
        'PySide6.QtGui.QLinearGradient',
        'PySide6.QtGui.QIcon',
        'PySide6.QtGui.QKeySequence',
        'PySide6.QtGui.QShortcut',
        'PySide6.QtGui.QDrag',
        'PySide6.QtGui.QAction',
        'win32gui',
        'win32api',
        'win32con',
        'win32process',
        'win32file',
        'win32security',
        'PIL',
        'PIL.Image',
        'PIL.ImageQt',
        'json',
        'pathlib',
        'subprocess',
        'dataclasses',
        'typing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'unittest', 'test', 'distutils', 'setuptools',
        'pkg_resources', 'email', 'http', 'urllib', 'xml', 'xmlrpc',
        'multiprocessing', 'concurrent', 'asyncio', 'ssl',
        'hmac', 'cryptography', 'matplotlib', 'numpy', 'scipy',
        'pandas', 'sklearn', 'tensorflow', 'torch', 'jupyter',
        'notebook', 'ipython', 'sympy', 'requests', 'aiohttp',
        'flask', 'django', 'fastapi', 'sqlalchemy', 'psycopg2',
        'mysql', 'sqlite3', 'redis', 'celery', 'gunicorn',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SuperLauncher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,  # No compression for better compatibility
    console=False,  # GUI application
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='template_app/assets/icons/icon.png' if os.path.exists('template_app/assets/icons/icon.png') else None,
    version_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=True,
    upx=False,
    upx_exclude=[],
    name='SuperLauncher',
)
